version: "3.3"
services:
  mongo-dev:
    image: mongo:4
    restart: unless-stopped
    command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - 27017:27017
  mongo-express-dev:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo-dev
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
